const express = require('express')
const authMiddleware = require('../middlewares/auth.middleware')
const router = express.Router()
const orderController = require('../controllers/adminOrder.controller')
const adminAuthMiddleware = require('../middlewares/adminAuth.middleware')
router.get('/', adminAuthMiddleware, orderController.getAllOrders)
router.put('/:orderId/place', adminAuthMiddleware, orderController.placeOrders)
router.put('/:orderId/pending', adminAuthMiddleware, orderController.pendingOrders)
router.put('/:orderId/confirmed', adminAuthMiddleware, orderController.confirmedOrders)
router.put('/:orderId/ship', adminAuthMiddleware, orderController.shipOrders)
router.put('/:orderId/deliver', adminAuthMiddleware, orderController.deliverOrders)
router.put('/:orderId/cancel', authMiddleware, orderController.cancelOrders)
router.put('/:orderId/payment', adminAuthMiddleware, orderController.confirmPaymentOrders)
router.put('/:orderId/complete', adminAuthMiddleware, orderController.completeOrders)
router.put('/:orderId/delete', adminAuthMiddleware, orderController.deleteOrders)
router.get('/statistics', adminAuthMiddleware, orderController.getOrderStats)
router.put("/:orderId/refund", authMiddleware, orderController.refundOrder)

module.exports = router